openapi: 3.0.0
info: 
  title: Sample API
  description: This is the description of the API 
  version: "1"

servers:
  - url: http://localhost:3001
    description: Local development
  - url: https://backend-sandy-eta.vercel.app

tags:
  - name: common
  - name: user
  - name: upload

paths:
  /health-check:
    get:
      tags:
        - common
      responses:
        200:
          description: Everything is good
        500:
          description: Something bad happened

  /api/user/signup:
    post:
      tags:
        - user
      summary: User Signup
      requestBody:
        description: User signup request
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                phoneNumber:
                  type: string
      responses:
        201:
          description: User created successfully
        500:
          description: Internal Server Error

  /api/user/login:
    post:
      tags:
        - user
      summary: User Login
      requestBody:
        description: User login request
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        401:
          description: Invalid credentials
        500:
          description: Internal Server Error
  /api/upload:

    post:
      tags:
        - upload
      summary: Upload a file to Amazon S3
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Confirmation message
                  location:
                    type: string
                    description: URL of the uploaded file on S3
        '400':
          description: Bad Request - No file uploaded
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
